Got upgrading working, but it is quite slow. Need to add disk space checks, and change status messages when upgrading

diff --git a/res/raw/patch b/res/raw/patch
--- a/res/raw/patch
+++ b/res/raw/patch
@@ -21,27 +21,41 @@
 # Usage: patch <busybox> <xdelta3> <pv> <temp fifo> <orig archive> <orig unpacked size> <patch> <new file> <new archive>
 # Doesn't check space
 
+echo "Patch script running"
+
 BB=$1
+echo "BB: $BB"
 
 XDELTA3=$2
+echo "xdelta3: $XDELTA3"
 
 PV=$3
+echo "pv: $PV"
 
 FIFO=$4
+echo "fifo: $FIFO"
 
 ORIG_GZ=$5
+echo "orig gz: $ORIG_GZ"
 ORIG_SIZE=$6
+echo "orig size: $ORIG_SIZE"
 
 PATCH=$7
+echo "patch: $PATCH"
 
 NEW=$8
+echo "new: $NEW"
 NEWGZ=$9
+echo "new gz: $NEWGZ"
 
 # Create pipe from gzip 
-$BB mkfifo $FIFO || $BB rm $FIFO || echo "Couldn't delete old fifo
+$BB mkfifo $FIFO || ($BB rm $FIFO && $BB mkfifo $FIFO) || echo "Couldn't delete old fifo"
 
 $BB cat $ORIG_GZ | $BB gzip -d > $FIFO &
+BG_PID="$!"
 
 $XDELTA3 -c -d -s $FIFO $PATCH | $PV -n -s $ORIG_SIZE | $BB tee $NEW | $BB gzip > $NEWGZ
 
-$BB rm $FIFO
+$BB rm $FIFO || echo "Failed to delete fifo"
+
+kill $BG_PID || echo "Couldn't kill BG thread. Probably already gone"
